import { Crop } from './types';

export const MOCK_CROPS: Crop[] = [
  {
    id: 'mock-1',
    farmer_id: 'mock-farmer-1',
    name: 'Basmati Rice',
    category: 'Grains',
    price_per_unit: 42,
    unit: 'kg',
    quantity_available: 500,
    harvest_date: '2026-07-15',
    location: 'Punjab',
    image_url: 'https://images.pexels.com/photos/18446086/pexels-photo-18446086.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Premium long-grain basmati rice, naturally sun-dried. Aromatic and fluffy when cooked.',
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'mock-2',
    farmer_id: 'mock-farmer-2',
    name: 'Hybrid Tomato',
    category: 'Vegetables',
    price_per_unit: 22,
    unit: 'kg',
    quantity_available: 300,
    harvest_date: '2026-08-10',
    location: 'Karnataka',
    image_url: 'https://images.pexels.com/photos/34635764/pexels-photo-34635764.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Fresh farm tomatoes, vine-ripened for maximum flavor. Ideal for retail and food service.',
    created_at: '2026-08-15T08:00:00Z',
  },
  {
    id: 'mock-3',
    farmer_id: 'mock-farmer-3',
    name: 'Alphonso Mango',
    category: 'Fruits',
    price_per_unit: 65,
    unit: 'kg',
    quantity_available: 200,
    harvest_date: '2026-06-20',
    location: 'Maharashtra',
    image_url: 'https://images.pexels.com/photos/28903096/pexels-photo-28903096.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'The king of mangoes — naturally ripened Alphonso with rich creamy pulp and intense aroma.',
    created_at: '2026-07-20T12:00:00Z',
  },
  {
    id: 'mock-4',
    farmer_id: 'mock-farmer-4',
    name: 'Potato (Chipsona)',
    category: 'Vegetables',
    price_per_unit: 18,
    unit: 'kg',
    quantity_available: 800,
    harvest_date: '2026-08-05',
    location: 'Uttar Pradesh',
    image_url: 'https://images.pexels.com/photos/8369485/pexels-photo-8369485.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'High-quality Chipsona potatoes with low sugar content, perfect for chips and processing.',
    created_at: '2026-08-10T09:00:00Z',
  },
  {
    id: 'mock-5',
    farmer_id: 'mock-farmer-5',
    name: 'Cotton (J-34)',
    category: 'Cash Crops',
    price_per_unit: 68,
    unit: 'kg',
    quantity_available: 1000,
    harvest_date: '2026-07-30',
    location: 'Gujarat',
    image_url: 'https://images.pexels.com/photos/13924870/pexels-photo-13924870.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Premium J-34 cotton variety with long staple length. Handpicked for quality assurance.',
    created_at: '2026-08-05T14:00:00Z',
  },
  {
    id: 'mock-6',
    farmer_id: 'mock-farmer-6',
    name: 'Red Onion',
    category: 'Vegetables',
    price_per_unit: 25,
    unit: 'kg',
    quantity_available: 600,
    harvest_date: '2026-08-12',
    location: 'Maharashtra',
    image_url: 'https://images.pexels.com/photos/10444827/pexels-photo-10444827.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Nashik red onions, naturally cured with tight skin. Long shelf life and pungent flavor.',
    created_at: '2026-08-18T07:00:00Z',
  },
  {
    id: 'mock-7',
    farmer_id: 'mock-farmer-7',
    name: 'Wheat (Sharbati)',
    category: 'Grains',
    price_per_unit: 30,
    unit: 'kg',
    quantity_available: 1200,
    harvest_date: '2026-04-15',
    location: 'Madhya Pradesh',
    image_url: 'https://images.pexels.com/photos/12873375/pexels-photo-12873375.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Premium Sharbati wheat known for its golden grain and high protein content. Stone-milled quality.',
    created_at: '2026-05-01T11:00:00Z',
  },
  {
    id: 'mock-8',
    farmer_id: 'mock-farmer-8',
    name: 'Banana (Cavendish)',
    category: 'Fruits',
    price_per_unit: 28,
    unit: 'kg',
    quantity_available: 400,
    harvest_date: '2026-08-18',
    location: 'Tamil Nadu',
    image_url: 'https://images.pexels.com/photos/15914440/pexels-photo-15914440.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Export-quality Cavendish bananas, uniformly ripened. Sweet taste with firm texture.',
    created_at: '2026-08-20T06:00:00Z',
  },
  {
    id: 'mock-9',
    farmer_id: 'mock-farmer-9',
    name: 'Red Chilli',
    category: 'Spices',
    price_per_unit: 95,
    unit: 'kg',
    quantity_available: 150,
    harvest_date: '2026-07-25',
    location: 'Andhra Pradesh',
    image_url: 'https://images.pexels.com/photos/39390/chili-pepper-red-spicy-drying-39390.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Sun-dried Teja red chillies with high pungency and vibrant color. Sorted and graded.',
    created_at: '2026-08-01T15:00:00Z',
  },
  {
    id: 'mock-10',
    farmer_id: 'mock-farmer-10',
    name: 'Tur Dal',
    category: 'Pulses',
    price_per_unit: 85,
    unit: 'kg',
    quantity_available: 250,
    harvest_date: '2026-06-10',
    location: 'Karnataka',
    image_url: 'https://images.pexels.com/photos/34940646/pexels-photo-34940646.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Unpolished whole tur dal (arhar). Rich in protein, naturally grown without pesticides.',
    created_at: '2026-07-01T10:00:00Z',
  },
  {
    id: 'mock-11',
    farmer_id: 'mock-farmer-11',
    name: 'Groundnut',
    category: 'Oilseeds',
    price_per_unit: 58,
    unit: 'kg',
    quantity_available: 350,
    harvest_date: '2026-07-10',
    location: 'Gujarat',
    image_url: 'https://images.pexels.com/photos/9799037/pexels-photo-9799037.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Bold variety groundnuts with high oil content. Cleaned and graded for quality.',
    created_at: '2026-07-25T13:00:00Z',
  },
  {
    id: 'mock-12',
    farmer_id: 'mock-farmer-12',
    name: 'Maize (Yellow)',
    category: 'Grains',
    price_per_unit: 22,
    unit: 'kg',
    quantity_available: 900,
    harvest_date: '2026-08-08',
    location: 'Punjab',
    image_url: 'https://images.pexels.com/photos/33989638/pexels-photo-33989638.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'High-yield yellow maize with uniform grain size. Ideal for poultry feed and industrial use.',
    created_at: '2026-08-12T09:00:00Z',
  },
];

export const MOCK_FARMER_NAMES: Record<string, { full_name: string; farm_name: string }> = {
  'mock-farmer-1': { full_name: 'Harjeet Singh', farm_name: 'Green Fields Farm' },
  'mock-farmer-2': { full_name: 'Ramesh Gowda', farm_name: 'Namma Hasiru' },
  'mock-farmer-3': { full_name: 'Suresh Patil', farm_name: 'Konkan Orchards' },
  'mock-farmer-4': { full_name: 'Vijay Yadav', farm_name: 'Doab Krishi' },
  'mock-farmer-5': { full_name: 'Kishan Patel', farm_name: 'Saurashtra Cotton' },
  'mock-farmer-6': { full_name: 'Anil Deshmukh', farm_name: 'Nashik Onion Co.' },
  'mock-farmer-7': { full_name: 'Mahendra Tomar', farm_name: 'Sharbati Farms' },
  'mock-farmer-8': { full_name: 'Karthik Reddy', farm_name: 'Cauvery Bananas' },
  'mock-farmer-9': { full_name: 'Lakshmi Naidu', farm_name: 'Guntur Spice Garden' },
  'mock-farmer-10': { full_name: 'Manjunath Rao', farm_name: 'Kalpavriksha' },
  'mock-farmer-11': { full_name: 'Bharat Modi', farm_name: 'Saurashtra Oilseeds' },
  'mock-farmer-12': { full_name: 'Gurpreet Brar', farm_name: 'Punjab Maize Co.' },
};
